= Migration of AWX to AAP 2.5 
:navtitle: Home

Introduction:

The Ansible Automation platform Application Migration: Free to Enterprise course, which aims to close the gap between enterprise-grade solutions from the open-source automation. With an emphasis on scalability, security, and advanced capabilities, this extensive course will walk you through the process of moving automation workflows from free tools to reliable corporate platforms. This training gives you the knowledge and abilities to guarantee a smooth transition, whether you're updating your automation ecosystem or bringing it into compliance with organizational requirements.

Duration: 40 Minutes

== Objectives

On completing this course, you should be able to:

- Implement the steps provided to guide application migration.
- Define and discuss the necessity for AWX to AAP 2.5 migration.
- Define the benefits of utilizing AAP 2.5 to migrate applications.
- Diagnose and rectify known issues in AWX application migrations.

== Prerequisites

This course assumes that you have the following prior experience:

* Knowledge on Ansible Automation Platform.
* Foundational Knowledge of Openshift and Linux. 

== Contributors

The PTL team acknowledges the valuable contributions of the following Red Hat associates:

- Hao Liu (SME)
- Sarvesh Pandit (Contributor)
- Amrinder Singh (Content Architect)
- Rutuja Deshmukh (Editor)
- Anna Swicegood (Learning Product Manager)

