site:
  title: "Ansible Web eXecutable (AWX) to Ansible Automation Platform 2.5 (AAP) Migration"
  start_page: awx-aap-migration::index.adoc

content:
  sources:
  - url: ./

asciidoc:
  attributes:
    page-pagination: true

ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui
